# Generated by Django 2.2.16 on 2022-12-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221206_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='f0llowing',
            new_name='following',
        ),
    ]
